name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      scary_version:
        description: 'Version of the application'
        required: true
        default: '1.0.0'

env:
  VERSION: ${{ github.event.inputs.scary_version }}

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set version
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          envsubst < stack.version.yml > stack.tmp.version.yml
          mv stack.tmp.version.yml stack.version.yml

      - name: deploy files
        uses: appleboy/scp-action@v0.1.3
        with:
            host: scarycaves.meancat.com
            username: deploy
            key: ${{ secrets.DO_DEPLOY_PRIVATE_KEY }}
            source: "./stack.yml,./stack.version.yml"
            target: /home/deploy

      - name: update stack on remote
        uses: appleboy/ssh-action@v1.2.0
        env:
          VERSION: ${{ env.VERSION }}
          DEPLOY_USERNAME: deploy
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          envs: VERSION,DEPLOY_USERNAME,DOCKER_USERNAME
          host: scarycaves.meancat.com
          username: deploy
          key: ${{ secrets.DO_DEPLOY_PRIVATE_KEY }}
          script_path: ./deploy_images.sh
