name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      scary_version:
        description: 'Version of the application'
        required: true
        default: '1.0.0'

env:
  VERSION: ${{ github.event.inputs.scary_version }}

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: deploy files
        uses: appleboy/scp-action@v0.1.3
        with:
            host: scarycaves.meancat.com
            username: ${{ secrets.DEPLOY_USERNAME }}
            key: ${{ secrets.DO_DEPLOY_PRIVATE_KEY }}
            source: ./stack.yml
            target: /home/${{ secrets.DEPLOY_USERNAME }}

      - name: update stack on remote
        uses: appleboy/ssh-action@v1.2.0
        env:
          VERSION: ${{ env.VERSION }}
          DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}
        with:
          host: scarycaves.meancat.com
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DO_DEPLOY_PRIVATE_KEY }}
          script_path: ./deploy_images.sh
