name: Build and Deploy to Docker and Production

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]
  workflow_dispatch: # allow from UI or API

env:
  VERSION: 1.0.${{ github.run_number }}

jobs:
  build-push-deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build ASP.NET image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/scary_aspnet:${{ env.VERSION }} ./ScaryCavesWeb

      - name: build Next.js image
        run: |
          docker build \
          --build-arg NEXT_PUBLIC_BASE_URL=https://scarycaves.meancat.com \
          --build-arg NEXT_PUBLIC_API_BASE_URL=https://scarycaves.meancat.com/api \
          -t ${{ secrets.DOCKER_USERNAME }}/scary_next:${{ env.VERSION }} ./scarycaves-next

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

      - name: push ASP.NET image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/scary_aspnet:${{ env.VERSION }}

      - name: push Next.js image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/scary_next:${{ env.VERSION }}

      - name: set version
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          envsubst < stack.version.yml > stack.tmp.version.yml
            mv stack.tmp.version.yml stack.version.yml

      - name: deploy files to remote
        uses: appleboy/scp-action@v0.1.3
        with:
          host: scarycaves.meancat.com
          username: deploy
          key: ${{ secrets.DO_DEPLOY_PRIVATE_KEY }}
          source: "./stack.yml,./stack.version.yml"
          target: /home/deploy

      - name: update stack on remote
        uses: appleboy/ssh-action@v1.2.0
        env:
          VERSION: ${{ env.VERSION }}
          DEPLOY_USERNAME: deploy
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          envs: VERSION,DEPLOY_USERNAME,DOCKER_USERNAME
          host: scarycaves.meancat.com
          username: deploy
          key: ${{ secrets.DO_DEPLOY_PRIVATE_KEY }}
          script_path: ./deploy_images.sh
