name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      scary_version:
        description: 'Version of the application'
        required: true
        default: '1.0.0'

env:
  VERSION: ${{ github.event.inputs.scary_version }}

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.DO_DEPLOY_PRIVATE_KEY }}

      - name: Verify SSH keys
        run: ssh-add -l

      - name: Deploy Stack
        env:
            VERSION: ${{ env.VERSION }}
            DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}
        run: ./deploy_remote.sh
