name: Deploy Production

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]
  workflow_dispatch: # allow from UI or API

env:
  VERSION: 1.0.${{ github.run_number }}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build ASP.NET image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/scary_aspnet:${{ env.VERSION }} ./ScaryCavesWeb
          docker images

      - name: build Next.js image
        run: |
          docker build \
          --build-arg NEXT_PUBLIC_BASE_URL=https://scarycaves.meancat.com \
          --build-arg NEXT_PUBLIC_API_BASE_URL=https://scarycaves.meancat.com/api \
          -t ${{ secrets.DOCKER_USERNAME }}/scary_next:${{ env.VERSION }} ./scarycaves-next
          docker images

  push:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

      - name: docker images
        run: docker images

      - name: push ASP.NET image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/scary_aspnet:${{ env.VERSION }}

      - name: push Next.js image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/scary_next:${{ env.VERSION }}
