name: Deploy Production

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]
  workflow_dispatch: # allow from UI or API

env:
  VERSION: 1.0.${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build aspnet
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/scary_aspnet:${{ env.VERSION }} ./ScaryCavesWeb

      - name: build next
        run: >
          docker build 
          --build-arg NEXT_PUBLIC_BASE_URL=https://scarycaves.meancat.com 
          --build-arg NEXT_PUBLIC_API_BASE_URL=https://scarycaves.meancat.com/api 
          -t ${{ secrets.DOCKER_USERNAME }}/scary_next:${{ env.VERSION }} ./scarycaves-next

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            ./ScaryCavesWeb/Dockerfile
            ./scarycaves-next/Dockerfile

  push:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: docker-images

      - name: Login to docker
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

      - name: Tag aspnet
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/scary_aspnet:${{ env.VERSION }} ${{ secrets.DOCKER_USERNAME }}/scary_aspnet:${{ env.VERSION }}

      - name: Tag next
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/scary_next:${{ env.VERSION }} ${{ secrets.DOCKER_USERNAME }}/scary_next:${{ env.VERSION }}

      - name: push aspnet
        run: docker push ${{ secrets.DOCKER_USERNAME }}/scary_aspnet:${{ env.VERSION }}

      - name: push next
        run: docker push ${{ secrets.DOCKER_USERNAME }}/scary_next:${{ env.VERSION }}
