name: Deploy Production

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]
  workflow_dispatch: # allow from UI or API

env:
  VERSION: 1.0.${{ github.run_number }}

jobs:
  build-push-deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build ASP.NET image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/scary_aspnet:${{ env.VERSION }} ./ScaryCavesWeb

      - name: build Next.js image
        run: |
          docker build \
          --build-arg NEXT_PUBLIC_BASE_URL=https://scarycaves.meancat.com \
          --build-arg NEXT_PUBLIC_API_BASE_URL=https://scarycaves.meancat.com/api \
          -t ${{ secrets.DOCKER_USERNAME }}/scary_next:${{ env.VERSION }} ./scarycaves-next

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

      - name: push ASP.NET image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/scary_aspnet:${{ env.VERSION }}

      - name: push Next.js image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/scary_next:${{ env.VERSION }}

      - name: Prepare SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.DO_DEPLOY_PRIVATE_KEY }}

      - name: Deploy Stack
        run: |
          export VERSION=${{ env.VERSION }}
          export DEPLOY_USERNAME=${{ secrets.DEPLOY_USERNAME }}
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          ./deploy_remote.sh
